"""Public contract-v1 symbols for framework-neutral Connectors."""

from .adapters import (
    AdapterEndpoint,
    AdapterFormat,
    AdapterOptions,
    ConfigScalar,
    ConfigValue,
    ConnectorAdapter,
    ProviderConfig,
    ProviderFactoryContext,
    WritePreflightAdapter,
    parse_adapter_endpoint,
    parse_adapter_format,
)
from .bounded_reads import (
    BOUNDED_ARROW_TABLE_READ_CAPABILITY,
    BoundedArrowTableReader,
    BoundedArrowTableReadResult,
    BoundedReadReceipt,
    BoundedTableReadRequest,
    ReadExtent,
)
from .capabilities import CapabilityManifest, TableMode
from .coordinates import (
    BaseConvention,
    BaseCoordinate,
    SheetConvention,
    SheetCoordinate,
    TableCoordinate,
)
from .errors import ConnectorError, ConnectorErrorCode
from .execution import (
    ExecutionRequest,
    ExecutionResult,
    PreparedOperation,
    SqlExecutor,
    StepExecutor,
)
from .identity import CapabilityIdentity, ConnectorIdentity
from .inspect import InspectRequest, TableInspection, TableInspector
from .names import (
    CAPABILITY_TABLE_READ_ARROW,
    CAPABILITY_TABLE_WRITE,
    CLI_CONFIG_DIRECTORY,
    CLI_CONFIG_ENV,
    CLI_CONFIG_FILENAME,
    CLI_CONFIG_SCHEMA_VERSION,
    CLI_PLUGIN_GROUP,
    CREDENTIAL_ACCESS_TOKEN,
    CREDENTIAL_TENANT_ACCESS_TOKEN,
    FORMAT_AUTO,
    FORMAT_TABLE,
    HOST_GOOGLE_DOCS,
    HOST_MAYBE,
    IF_EXISTS_APPEND,
    IF_EXISTS_ERROR,
    IF_EXISTS_REPLACE,
    OPTION_TIMEOUT_SECONDS,
    PACKAGE_NAMESPACE,
    PROCESS_PLUGIN_GROUP,
    PROVIDER_CSV,
    PROVIDER_DBT,
    PROVIDER_EXCEL,
    PROVIDER_FEISHU_BITABLE,
    PROVIDER_GOOGLE_SHEETS,
    PROVIDER_IDS,
    PROVIDER_JSON,
    PROVIDER_JSONL,
    PROVIDER_LOCAL_FILES,
    PROVIDER_MAYBE_SHEET,
    PROVIDER_PLUGIN_GROUP,
    PROVIDER_POSTGRES,
    PROVIDER_SQLITE,
    SCHEME_FEISHU,
    SCHEME_FILE,
    SCHEME_GSHEETS,
    SCHEME_HTTPS,
    SCHEME_MANAGED_CSV,
    SCHEME_MANAGED_XLSX,
    SCHEME_MAYBE,
    SCHEME_MD,
    SCHEME_POSTGRESQL,
    SCHEME_XLSX,
    SETTING_BINARY,
    SETTING_ENDPOINT,
    XDG_CONFIG_HOME_ENV,
)
from .plugins import PluginDescriptor, PluginFactory
from .read import (
    ArrowReadResult,
    ArrowTableReader,
    PolarsReadResult,
    PolarsTableReader,
    TableReadRequest,
)
from .receipts import NeutralReceipt
from .resolve import (
    ResolveContext,
    ResolvedTable,
    ResourceLimits,
    URIResolver,
)
from .scalars import Scalar
from .storage import TableWriter, TableWriteRequest, TableWriteResult, TransactionalStore
from .uri import TableURI

__all__ = [
    "BaseConvention",
    "AdapterEndpoint",
    "AdapterFormat",
    "AdapterOptions",
    "ConfigScalar",
    "ConfigValue",
    "ConnectorAdapter",
    "BOUNDED_ARROW_TABLE_READ_CAPABILITY",
    "BoundedArrowTableReadResult",
    "BoundedArrowTableReader",
    "BoundedReadReceipt",
    "BoundedTableReadRequest",
    "BaseCoordinate",
    "CapabilityIdentity",
    "CapabilityManifest",
    "ConnectorError",
    "ConnectorErrorCode",
    "ConnectorIdentity",
    "InspectRequest",
    "NeutralReceipt",
    "ArrowReadResult",
    "ArrowTableReader",
    "PolarsReadResult",
    "PolarsTableReader",
    "PluginDescriptor",
    "PluginFactory",
    "PACKAGE_NAMESPACE",
    "CLI_PLUGIN_GROUP",
    "CLI_CONFIG_DIRECTORY",
    "CLI_CONFIG_ENV",
    "CLI_CONFIG_FILENAME",
    "CLI_CONFIG_SCHEMA_VERSION",
    "XDG_CONFIG_HOME_ENV",
    "CAPABILITY_TABLE_READ_ARROW",
    "CAPABILITY_TABLE_WRITE",
    "CREDENTIAL_ACCESS_TOKEN",
    "CREDENTIAL_TENANT_ACCESS_TOKEN",
    "FORMAT_AUTO",
    "FORMAT_TABLE",
    "IF_EXISTS_APPEND",
    "IF_EXISTS_ERROR",
    "IF_EXISTS_REPLACE",
    "PROCESS_PLUGIN_GROUP",
    "PROVIDER_PLUGIN_GROUP",
    "PROVIDER_CSV",
    "PROVIDER_JSON",
    "PROVIDER_JSONL",
    "PROVIDER_EXCEL",
    "PROVIDER_LOCAL_FILES",
    "PROVIDER_SQLITE",
    "PROVIDER_IDS",
    "PROVIDER_POSTGRES",
    "PROVIDER_GOOGLE_SHEETS",
    "PROVIDER_FEISHU_BITABLE",
    "PROVIDER_MAYBE_SHEET",
    "PROVIDER_DBT",
    "SCHEME_FILE",
    "SCHEME_XLSX",
    "SCHEME_GSHEETS",
    "SCHEME_HTTPS",
    "SCHEME_FEISHU",
    "SCHEME_MAYBE",
    "SCHEME_MANAGED_CSV",
    "SCHEME_MANAGED_XLSX",
    "SCHEME_POSTGRESQL",
    "SCHEME_MD",
    "SETTING_BINARY",
    "SETTING_ENDPOINT",
    "OPTION_TIMEOUT_SECONDS",
    "HOST_GOOGLE_DOCS",
    "HOST_MAYBE",
    "ResolvedTable",
    "ResolveContext",
    "ResourceLimits",
    "ReadExtent",
    "Scalar",
    "SheetConvention",
    "SheetCoordinate",
    "TableCoordinate",
    "TableMode",
    "TableInspection",
    "TableInspector",
    "TableReadRequest",
    "URIResolver",
    "TableURI",
    "ExecutionRequest",
    "ExecutionResult",
    "PreparedOperation",
    "StepExecutor",
    "SqlExecutor",
    "TableWriteRequest",
    "TableWriteResult",
    "TableWriter",
    "TransactionalStore",
    "ProviderConfig",
    "ProviderFactoryContext",
    "WritePreflightAdapter",
    "parse_adapter_endpoint",
    "parse_adapter_format",
]
