"""Public contract-v1 symbols for framework-neutral Connectors."""

from .bounded_reads import (
    BOUNDED_ARROW_TABLE_READ_CAPABILITY,
    BoundedArrowTableReader,
    BoundedArrowTableReadResult,
    BoundedReadReceipt,
    BoundedTableReadRequest,
    ReadExtent,
)
from .capabilities import CapabilityManifest, TableMode
from .coordinates import (
    BaseConvention,
    BaseCoordinate,
    SheetConvention,
    SheetCoordinate,
    TableCoordinate,
)
from .errors import ConnectorError, ConnectorErrorCode
from .execution import (
    ExecutionRequest,
    ExecutionResult,
    PreparedOperation,
    SqlExecutor,
    StepExecutor,
)
from .identity import CapabilityIdentity, ConnectorIdentity
from .inspect import InspectRequest, TableInspection, TableInspector
from .names import (
    CLI_PLUGIN_GROUP,
    HOST_GOOGLE_DOCS,
    HOST_MAYBE,
    PACKAGE_NAMESPACE,
    PROCESS_PLUGIN_GROUP,
    PROVIDER_CSV,
    PROVIDER_DBT,
    PROVIDER_EXCEL,
    PROVIDER_FEISHU_BITABLE,
    PROVIDER_GOOGLE_SHEETS,
    PROVIDER_JSON,
    PROVIDER_JSONL,
    PROVIDER_LOCAL_FILES,
    PROVIDER_MAYBE_SHEET,
    PROVIDER_PLUGIN_GROUP,
    PROVIDER_POSTGRES,
    PROVIDER_SQLITE,
    SCHEME_FEISHU,
    SCHEME_FILE,
    SCHEME_GSHEETS,
    SCHEME_HTTPS,
    SCHEME_MANAGED_CSV,
    SCHEME_MANAGED_XLSX,
    SCHEME_MAYBE,
    SCHEME_MD,
    SCHEME_POSTGRESQL,
    SCHEME_XLSX,
)
from .plugins import PluginDescriptor, PluginFactory
from .read import (
    ArrowReadResult,
    ArrowTableReader,
    PolarsReadResult,
    PolarsTableReader,
    TableReadRequest,
)
from .receipts import NeutralReceipt
from .resolve import (
    ResolveContext,
    ResolvedTable,
    ResourceLimits,
    URIResolver,
)
from .scalars import Scalar
from .storage import TableWriter, TableWriteRequest, TableWriteResult, TransactionalStore
from .uri import TableURI

__all__ = [
    "BaseConvention",
    "BOUNDED_ARROW_TABLE_READ_CAPABILITY",
    "BoundedArrowTableReadResult",
    "BoundedArrowTableReader",
    "BoundedReadReceipt",
    "BoundedTableReadRequest",
    "BaseCoordinate",
    "CapabilityIdentity",
    "CapabilityManifest",
    "ConnectorError",
    "ConnectorErrorCode",
    "ConnectorIdentity",
    "InspectRequest",
    "NeutralReceipt",
    "ArrowReadResult",
    "ArrowTableReader",
    "PolarsReadResult",
    "PolarsTableReader",
    "PluginDescriptor",
    "PluginFactory",
    "PACKAGE_NAMESPACE",
    "CLI_PLUGIN_GROUP",
    "PROCESS_PLUGIN_GROUP",
    "PROVIDER_PLUGIN_GROUP",
    "PROVIDER_CSV",
    "PROVIDER_JSON",
    "PROVIDER_JSONL",
    "PROVIDER_EXCEL",
    "PROVIDER_LOCAL_FILES",
    "PROVIDER_SQLITE",
    "PROVIDER_POSTGRES",
    "PROVIDER_GOOGLE_SHEETS",
    "PROVIDER_FEISHU_BITABLE",
    "PROVIDER_MAYBE_SHEET",
    "PROVIDER_DBT",
    "SCHEME_FILE",
    "SCHEME_XLSX",
    "SCHEME_GSHEETS",
    "SCHEME_HTTPS",
    "SCHEME_FEISHU",
    "SCHEME_MAYBE",
    "SCHEME_MANAGED_CSV",
    "SCHEME_MANAGED_XLSX",
    "SCHEME_POSTGRESQL",
    "SCHEME_MD",
    "HOST_GOOGLE_DOCS",
    "HOST_MAYBE",
    "ResolvedTable",
    "ResolveContext",
    "ResourceLimits",
    "ReadExtent",
    "Scalar",
    "SheetConvention",
    "SheetCoordinate",
    "TableCoordinate",
    "TableMode",
    "TableInspection",
    "TableInspector",
    "TableReadRequest",
    "URIResolver",
    "TableURI",
    "ExecutionRequest",
    "ExecutionResult",
    "PreparedOperation",
    "StepExecutor",
    "SqlExecutor",
    "TableWriteRequest",
    "TableWriteResult",
    "TableWriter",
    "TransactionalStore",
]
