"""Polars-first OTC SDK."""

from .model import (
    BaseModeDestination,
    BaseModeTableAddress,
    DatabaseTableAddress,
    DirectDestination,
    DirectTableAddress,
    ExistingTableAddress,
    QualifiedTableName,
    SchemaPolicy,
    SheetModeDestination,
    SheetModeTableAddress,
    SheetRangeSource,
    TableDestination,
    TableMode,
)
from .predicates import PortablePredicate, PredicateKind, all_rows
from .result import (
    CommitState,
    ErrorCode,
    ErrorInfo,
    OperationResult,
    OperationWarning,
    OTCError,
    Outcome,
    Receipt,
    ReconciliationReference,
    VerificationState,
)

__all__ = [
    "BaseModeDestination",
    "BaseModeTableAddress",
    "CommitState",
    "DatabaseTableAddress",
    "DirectDestination",
    "DirectTableAddress",
    "ErrorCode",
    "ErrorInfo",
    "ExistingTableAddress",
    "OTCError",
    "OperationResult",
    "OperationWarning",
    "Outcome",
    "PortablePredicate",
    "PredicateKind",
    "QualifiedTableName",
    "Receipt",
    "ReconciliationReference",
    "SchemaPolicy",
    "SheetModeDestination",
    "SheetModeTableAddress",
    "SheetRangeSource",
    "TableDestination",
    "TableMode",
    "VerificationState",
    "all_rows",
]
