"""Polars-first OTC SDK."""

from .client import Client
from .config import ClientConfig, CredentialBinding, load_client_config, resolve_config_path
from .connector import LegacyConnectorAdapterBridge, TableConnector
from .credentials import (
    CredentialLease,
    CredentialResolver,
    EnvironmentCredentialResolver,
    apply_credential_overrides,
    parse_credential_overrides,
)
from .model import (
    BaseModeDestination,
    BaseModeTableAddress,
    DatabaseTableAddress,
    DirectDestination,
    DirectTableAddress,
    ExistingTableAddress,
    QualifiedTableName,
    SchemaPolicy,
    SheetModeDestination,
    SheetModeTableAddress,
    SheetRangeSource,
    TableDestination,
    TableMode,
)
from .predicates import PortablePredicate, PredicateKind, all_rows
from .query import Query, QueryLane, SqlResourceLimits
from .registry import (
    ConfiguredPlugin,
    ConnectorRegistry,
    discover_configured_plugins,
    discover_descriptors,
)
from .result import (
    CommitState,
    ErrorCode,
    ErrorInfo,
    OperationResult,
    OperationWarning,
    OTCError,
    Outcome,
    Receipt,
    ReconciliationReference,
    VerificationState,
)
from .sql import NativeSql, NativeSqlResourceLimits, PolarsPlanMapper, sql
from .table import CapabilitySet, Table, TableBinding, TableInspection, TableTransaction
from .temporal import (
    AbortDisposition,
    AggregateFunction,
    AggregateMeasure,
    CalendarBucket,
    FillMode,
    FillRule,
    FixedBucket,
    ManagedSnapshot,
    ManagedStage,
    TemporalConnectorExtension,
    TemporalResourceLimits,
    TemporalTableDescriptor,
    TimeSeriesView,
)

__all__ = [
    "AbortDisposition",
    "AggregateFunction",
    "AggregateMeasure",
    "BaseModeDestination",
    "BaseModeTableAddress",
    "CapabilitySet",
    "CalendarBucket",
    "Client",
    "ClientConfig",
    "CommitState",
    "ConfiguredPlugin",
    "ConnectorRegistry",
    "CredentialLease",
    "CredentialBinding",
    "CredentialResolver",
    "DatabaseTableAddress",
    "DirectDestination",
    "DirectTableAddress",
    "EnvironmentCredentialResolver",
    "ErrorCode",
    "ErrorInfo",
    "ExistingTableAddress",
    "FillMode",
    "FillRule",
    "FixedBucket",
    "LegacyConnectorAdapterBridge",
    "ManagedSnapshot",
    "ManagedStage",
    "NativeSql",
    "NativeSqlResourceLimits",
    "OTCError",
    "OperationResult",
    "OperationWarning",
    "Outcome",
    "PolarsPlanMapper",
    "PortablePredicate",
    "PredicateKind",
    "Query",
    "QueryLane",
    "QualifiedTableName",
    "Receipt",
    "ReconciliationReference",
    "SchemaPolicy",
    "SheetModeDestination",
    "SheetModeTableAddress",
    "SheetRangeSource",
    "SqlResourceLimits",
    "Table",
    "TableBinding",
    "TableConnector",
    "TableDestination",
    "TableInspection",
    "TableMode",
    "TemporalConnectorExtension",
    "TemporalResourceLimits",
    "TemporalTableDescriptor",
    "TableTransaction",
    "TimeSeriesView",
    "VerificationState",
    "all_rows",
    "apply_credential_overrides",
    "discover_configured_plugins",
    "discover_descriptors",
    "load_client_config",
    "parse_credential_overrides",
    "resolve_config_path",
    "sql",
]
