"""Polars-first OTC SDK."""

from .client import Client
from .config import ClientConfig, CredentialBinding, load_client_config, resolve_config_path
from .connector import LegacyConnectorAdapterBridge, TableConnector
from .credentials import (
    CredentialLease,
    CredentialResolver,
    EnvironmentCredentialResolver,
    apply_credential_overrides,
    parse_credential_overrides,
)
from .model import (
    BaseModeDestination,
    BaseModeTableAddress,
    DatabaseTableAddress,
    DirectDestination,
    DirectTableAddress,
    ExistingTableAddress,
    QualifiedTableName,
    SchemaPolicy,
    SheetModeDestination,
    SheetModeTableAddress,
    SheetRangeSource,
    TableDestination,
    TableMode,
)
from .predicates import PortablePredicate, PredicateKind, all_rows
from .registry import ConfiguredPlugin, ConnectorRegistry, discover_configured_plugins
from .result import (
    CommitState,
    ErrorCode,
    ErrorInfo,
    OperationResult,
    OperationWarning,
    OTCError,
    Outcome,
    Receipt,
    ReconciliationReference,
    VerificationState,
)
from .table import CapabilitySet, Table, TableBinding, TableInspection, TableTransaction

__all__ = [
    "BaseModeDestination",
    "BaseModeTableAddress",
    "CapabilitySet",
    "Client",
    "ClientConfig",
    "CommitState",
    "ConfiguredPlugin",
    "ConnectorRegistry",
    "CredentialLease",
    "CredentialBinding",
    "CredentialResolver",
    "DatabaseTableAddress",
    "DirectDestination",
    "DirectTableAddress",
    "EnvironmentCredentialResolver",
    "ErrorCode",
    "ErrorInfo",
    "ExistingTableAddress",
    "LegacyConnectorAdapterBridge",
    "OTCError",
    "OperationResult",
    "OperationWarning",
    "Outcome",
    "PortablePredicate",
    "PredicateKind",
    "QualifiedTableName",
    "Receipt",
    "ReconciliationReference",
    "SchemaPolicy",
    "SheetModeDestination",
    "SheetModeTableAddress",
    "SheetRangeSource",
    "Table",
    "TableBinding",
    "TableConnector",
    "TableDestination",
    "TableInspection",
    "TableMode",
    "TableTransaction",
    "VerificationState",
    "all_rows",
    "apply_credential_overrides",
    "discover_configured_plugins",
    "load_client_config",
    "parse_credential_overrides",
    "resolve_config_path",
]
