"""Portable temporal contracts for Open Table Connector."""

from .capabilities import ALL_CAPABILITIES
from .descriptor import (
    DuplicatePolicy,
    TemporalOrdering,
    TemporalTableDescriptor,
    TimestampPrecision,
    descriptor_from_wire,
    temporal_descriptor_hash,
)
from .plan import (
    AggregateFunction,
    AggregateMeasure,
    AsOf,
    BucketAggregate,
    CalendarBucket,
    CalendarUnit,
    FillMode,
    FillRule,
    FixedBucket,
    GapFill,
    Latest,
    OrderDirection,
    OrderKey,
    PortableTemporalPlan,
    ResourceBounds,
    ScanRange,
    TagOperator,
    TagPredicate,
    plan_from_wire,
    portable_plan_hash,
    validate_plan_for_descriptor,
)

__all__ = [
    "ALL_CAPABILITIES",
    "AggregateFunction",
    "AggregateMeasure",
    "AsOf",
    "BucketAggregate",
    "CalendarBucket",
    "CalendarUnit",
    "DuplicatePolicy",
    "FillMode",
    "FillRule",
    "FixedBucket",
    "GapFill",
    "Latest",
    "OrderDirection",
    "OrderKey",
    "PortableTemporalPlan",
    "ResourceBounds",
    "ScanRange",
    "TagOperator",
    "TagPredicate",
    "TemporalOrdering",
    "TemporalTableDescriptor",
    "TimestampPrecision",
    "descriptor_from_wire",
    "plan_from_wire",
    "portable_plan_hash",
    "temporal_descriptor_hash",
    "validate_plan_for_descriptor",
]
