"""Portable temporal contracts for Open Table Connector."""

from .capabilities import ALL_CAPABILITIES
from .buckets import calendar_bucket_start, fixed_bucket_start
from .descriptor import (
    DuplicatePolicy,
    TemporalOrdering,
    TemporalTableDescriptor,
    TimestampPrecision,
    descriptor_from_wire,
    temporal_descriptor_hash,
)
from .evaluator import PolarsTemporalExecutor, TemporalSource
from .lowering import PreparedTemporalQuery
from .plan import (
    AggregateFunction,
    AggregateMeasure,
    AsOf,
    BucketAggregate,
    CalendarBucket,
    CalendarUnit,
    FillMode,
    FillRule,
    FixedBucket,
    GapFill,
    Latest,
    OrderDirection,
    OrderKey,
    PortableTemporalPlan,
    ResourceBounds,
    ScanRange,
    TagOperator,
    TagPredicate,
    plan_from_wire,
    portable_plan_hash,
    validate_plan_for_descriptor,
)
from .precision import arrow_time_bounds, storage_to_timestamp, timestamp_to_storage
from .receipts import (
    AbortDisposition,
    ExecutionLocation,
    ManagedAbortReceipt,
    ManagedCommitReceipt,
    ManagedReadbackReceipt,
    ManagedStageReceipt,
    TemporalReceipt,
    TimeRange,
    VisibilityGuarantee,
)
from .storage import (
    ArrowArtifactReference,
    ManagedAbortRequest,
    ManagedCommitRequest,
    ManagedReadbackRequest,
    ManagedReadbackResult,
    ManagedStageRequest,
    ManagedTemporalStore,
    PortableTemporalExecutor,
    TemporalErrorCode,
    TemporalExtensionError,
    TemporalExecutionRequest,
    TemporalExecutionResult,
    validate_stage_retry,
)

__all__ = [
    "ALL_CAPABILITIES",
    "AbortDisposition",
    "AggregateFunction",
    "AggregateMeasure",
    "ArrowArtifactReference",
    "AsOf",
    "BucketAggregate",
    "CalendarBucket",
    "CalendarUnit",
    "DuplicatePolicy",
    "ExecutionLocation",
    "FillMode",
    "FillRule",
    "FixedBucket",
    "GapFill",
    "Latest",
    "ManagedAbortReceipt",
    "ManagedAbortRequest",
    "ManagedCommitReceipt",
    "ManagedCommitRequest",
    "ManagedReadbackReceipt",
    "ManagedReadbackRequest",
    "ManagedReadbackResult",
    "ManagedStageReceipt",
    "ManagedStageRequest",
    "ManagedTemporalStore",
    "OrderDirection",
    "OrderKey",
    "PortableTemporalPlan",
    "PortableTemporalExecutor",
    "PolarsTemporalExecutor",
    "PreparedTemporalQuery",
    "ResourceBounds",
    "ScanRange",
    "TagOperator",
    "TagPredicate",
    "TemporalOrdering",
    "TemporalErrorCode",
    "TemporalExtensionError",
    "TemporalExecutionRequest",
    "TemporalExecutionResult",
    "TemporalReceipt",
    "TemporalSource",
    "TemporalTableDescriptor",
    "TimeRange",
    "TimestampPrecision",
    "calendar_bucket_start",
    "descriptor_from_wire",
    "fixed_bucket_start",
    "plan_from_wire",
    "portable_plan_hash",
    "temporal_descriptor_hash",
    "validate_plan_for_descriptor",
    "validate_stage_retry",
    "arrow_time_bounds",
    "storage_to_timestamp",
    "timestamp_to_storage",
    "VisibilityGuarantee",
]
